steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/media:$COMMIT_SHA', '.']

  # Step 2: Push to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/media:$COMMIT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/media:$COMMIT_SHA'
